services:
  mysql:
    image: mysql:8.4.7
    container_name: mysql-estudos
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma-estudos
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data: